name: PR Comment

on:
  issue_comment:
    types: [ created ]

jobs:
  something:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - id: echo
        run: echo "foo" | tee output.log
        run: echo "::set-output name=bar::`cat output.log`"
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🤖 \n ${{ steps.echo.outputs.bar }} \n ${{ github.event.comment.body }}"
            })