name: Pull Request

# This can be used to test PRs

on:
  pull_request:

jobs:
  multi-line:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/scripts/output-multi.sh | tee output.log
        shell: bash
      - id: cat
        run: echo "::set-output name=log::(multiline doesn't work w/output)"
      - run: echo "FULL=<<EOF" >> $GITHUB_ENV
      - run: cat output.log >> $GITHUB_ENV
      - run: echo "EOF" >> $GITHUB_ENV
      - name: "Notify"
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            🤖 
            ```
            Test:
              
            ```
            <details><summary>Test</summary>

            ```
            ${{ env.full }}
            ```

            </details>

    outputs:
      log: ${{ steps.cat.outputs.log }}
  echo:
    runs-on: ubuntu-latest
    needs: multi-line
    steps:
      - run: echo '${{needs.json.outputs.log}}'