name: Pull Request

# This can be used to test PRs

on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - run: git log -1
      - run: cat README.md
      - uses: actions/checkout@v3 
        with:
          ref: main
      - run: git log -1
      - run: cat README.md
