name: Pull Request

# This can be used to test PRs

on:
  pull_request:
  workflow_dispatch:

jobs:
  python:
    name: "python"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: "deps"
        run: |
          python --version
          python -c 'print("hello world")'
          python -m pip install --upgrade pip
          pip install -r boto3
          pip list
