name: Pull Request

# This can be used to test PRs

on:
  pull_request:

jobs:
  multi-line:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/scripts/output-multi.sh | tee output.log
        shell: bash
      - id: cat
        run: echo "::set-output name=log::`cat output.log`"
    outputs:
      log: ${{ steps.cat.outputs.log }}
  echo:
    runs-on: ubuntu-latest
    needs: multi-line
    steps:
      - run: echo '${{needs.json.outputs.log}}'