name: Reusable Workflow

on:
  workflow_call:
    inputs:
      incoming:
        type: string
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The incoming input is ${{ inputs.incoming }}"
