name: Workflow Dispatch

on: 
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: null

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo The branch is ${{ inputs.branch }} 
